---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - image: gcr.io/harsha-346511/centos:latest
      name: web-server-container
      ports:
      - containerPort: 8080
